---
create_user: ehennenfent
user_name: Eric Hennenfent
user_email: eric.hennenfent@trailofbits.com
local_key: "{{ lookup('env','HOME') + '/.ssh/id_ed25519' }}"
local_key_contents: "{{ lookup('file', local_key + '.pub' )}}"
sys_packages: [ 'curl', 'zsh', 'git', 'python3', 'python3-pip', 'python3-dev']
