# disable starship from forcing a new line to be taken. Solved the empty line 
# at start of terminal
add_newline = false

[line_break]
disabled = true

# Replace the "❯" symbol in the prompt with "➟"
[character]      # The name of the module we are configuring is "character"
success_symbol = "[➟](bold green)" 
error_symbol = "[➟](bold red)" 

[aws]
disabled = true

[gcloud]
disabled = true

[time]
enabled = true